<a href="https://colab.research.google.com/github/olgOk/XanaduTraining/blob/master/Xanadu1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install strawberryfields

In [2]:
import strawberryfields as sf
from strawberryfields import ops
import numpy as np

In [3]:
prog = sf.Program(2)
with prog.context as q:
  ops.Fock(2)|q[0]
  ops.Fock(1)|q[1]
  ops.BSgate(0.2, 0.1)|q
  ops.MeasureFock()|q

eng = sf.Engine("fock", backend_options={"cutoff_dim":5})
result = eng.run(prog)
print(np.sum(result.samples))

3


In [4]:
prog1 = sf.Program(8)
with prog1.context as q:
  ops.S2gate(1.0) | (q[0], q[4])
  ops.S2gate(1.0) | (q[1], q[5])
  ops.S2gate(1.0) | (q[3], q[7])
  ops.MeasureFock()|q

eng = sf.Engine("gaussian")
result = eng.run(prog1, shots=5)
print(result.samples)

/usr/local/lib/python3.6/dist-packages/strawberryfields/backends/gaussianbackend/backend.py:232: UserWarning: Cannot simulate non-Gaussian states. Conditional state after Fock measurement has not been updated.


[[0 0 0 2 0 0 0 2]
 [0 0 0 2 0 0 0 2]
 [2 3 0 2 2 3 0 2]
 [2 0 0 1 2 0 0 1]
 [0 0 0 0 0 0 0 0]]


In [5]:
sf.store_account("qUOm1ptO039jCzVTTEUSd9SHZwkAs5dI8Rj8eIAZ")
sf.ping()

You have successfully authenticated to the platform!


In [9]:
eng=sf.RemoteEngine("X8")
result = eng.run(prog1, shots=5)
mes = result.samples
print(mes)

2020-07-15 15:58:09,153 - INFO - Job 18d4495c-da5a-4551-9c91-2a011f89d8cb was successfully submitted.
2020-07-15 15:58:35,194 - INFO - The remote job 18d4495c-da5a-4551-9c91-2a011f89d8cb has been completed.


[[0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 1 1 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [10]:
from strawberryfields.utils import random_interferometer 

prog = sf.Program(8, name="remote_job")
U = random_interferometer(4)
​
with prog.context as q:
    # Initial squeezed states
    # Allowed values are r=1.0 or r=0.0
    ops.S2gate(1.0) | (q[0], q[4])
    ops.S2gate(1.0) | (q[1], q[5])
    ops.S2gate(1.0) | (q[3], q[7])
​
    # Interferometer on the signal modes (0-3)
    ops.Interferometer(U) | (q[0], q[1], q[2], q[3])
    ops.BSgate(0.543, 0.123) | (q[2], q[0])
    ops.Rgate(0.453) | q[1]
    ops.MZgate(0.65, -0.54) | (q[2], q[3])
​
    # *Same* interferometer on the idler modes (4-7)
    ops.Interferometer(U) | (q[4], q[5], q[6], q[7])
    ops.BSgate(0.543, 0.123) | (q[6], q[4])
    ops.Rgate(0.453) | q[5]
    ops.MZgate(0.65, -0.54) | (q[6], q[7])
​
    ops.MeasureFock() | q
​
eng = sf.RemoteEngine("X8")
results = eng.run(prog, shots=1000)
print(results)


SyntaxError: ignored